# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/Infrastructure available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    Payman\Infrastructure\:
        resource: '../src/Infrastructure/'
        exclude:
            - '../src/Infrastructure/Framework/Kernel.php'

    Payman\Application\:
        resource: '../src/Application/'
        # Have to exclude those DTOs explicitly here.
        # Maybe there's some mask definition to avoid listing of all the DTOs?
        exclude:
            - '../src/Application/CreatePaymentPlan/CreatePaymentPlan.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    Payman\Infrastructure\Database\PaymentPlanRepositoryUsingDBAL:
        public: true

    Payman\Infrastructure\Database\PaymentYearRepositoryUsingDBAL:
        public: true

    Payman\Infrastructure\Database\StudentRepositoryUsingDBAL:
        public: true

    Payman\Infrastructure\Database\PaymentRepositoryUsingDBAL:
        public: true

    Payman\Infrastructure\Database\GetPaymentYearsUsingDBAL:
        public: true

    Payman\Infrastructure\Database\SchemaSetup:
        public: true

    Payman\Application\CreatePaymentPlan\CreatePaymentPlanService: '@Payman\Application\CreatePaymentPlan\CreatePaymentPlanHandler'
    Payman\Domain\Model\PaymentPlan\PaymentPlanRepository: '@Payman\Infrastructure\Database\PaymentPlanRepositoryUsingDBAL'
    Payman\Domain\Model\PaymentYear\PaymentYearRepository: '@Payman\Infrastructure\Database\PaymentYearRepositoryUsingDBAL'
    Payman\Domain\Model\Student\StudentRepository: '@Payman\Infrastructure\Database\StudentRepositoryUsingDBAL'
    Payman\Domain\Model\Payment\PaymentRepository: '@Payman\Infrastructure\Database\PaymentRepositoryUsingDBAL'
    Payman\Application\ListPaymentPlans\PaymentPlans: '@Payman\Infrastructure\Database\PaymentPlansUsingDBAL'
